### ISSUE TITLE
[v2] - Failed to resolve component warnings

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#162]
**Describe the bug**
Since we are using a Custom Renderer, the main instances of Vue don't recognize the Tres components and throw these annoying warnings that will confuse users.

One way around this is to add this to the `vite.config.ts`:

```
plugins: [vue({
    template: {
      compilerOptions: {
        isCustomElement: tag => tag.startsWith('Tres') && tag !== 'TresCanvas',
      },
    },
  })],
```
But that's not ideal.

**Expected behavior**
No warnings

**Screenshots**
<img width="803" alt="Screenshot 2023-03-23 at 06 15 08" src="https://user-images.githubusercontent.com/4699008/227110134-44644ecb-367b-4fe4-b071-8e3b645611ce.png">

**System Info**
Output of `npx envinfo --system --npmPackages '{vite,@tresjs/*, three, vue}' --binaries --browsers` 

**Additional context**

**Comment by arbaev** [comment]
I just want to note that if you are using Quasar + Vite, then to solve the problem, the code must be inserted into viteVuePluginOptions in `quasar.config.js` file:
```javascript
      viteVuePluginOptions: {
        template: {
          compilerOptions: {
            isCustomElement: (tag) =>
              tag.startsWith("Tres") && tag !== "TresCanvas",
          },
        },
      },
```
