### ISSUE TITLE
Calling `pause` immediately after `onLoop` doesn't do anything

### ISSUE THREAD

**Issue by callumacrae** [Tresjs/tres#251]
**Describe the bug**

When using `useRenderLoop`, immediately calling `pause` doesn't cause the animation to be initially paused:

```js
const { onLoop, pause } = useRenderLoop();
onLoop(() => {
  if (boxMeshRef.value) {
    boxMeshRef.value.rotation.y += 0.01;
  }
});
pause();
```

I'd expect the above code to result in an animation that doesn't run until `play()` is ran, but instead, it's as if `pause()` was never called.

The following also don't work:

- Calling `pause()` in a watcher on `boxMeshRef.value`
- Calling `pause()` in any watcher with `immediate: true`
- Calling `pause()` in `onMounted()`

The only workaround I've found is to call `pause()` in a `nextTick()` callback.

**Reproduction**

https://stackblitz.com/edit/tresjs-basic-q53da8?file=src/components/TheExperience.vue

**System Info**

```
  System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 878.45 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Safari: 16.3
  npmPackages:
    @tresjs/cientos: ^2.0.0-rc.1 => 2.0.0-rc.1
    @tresjs/core: ^2.0.0-rc.2 => 2.0.0-rc.2
    vite: ^4.0.0 => 4.0.1
```

**Comment by alvarosabu** [comment]
The new recommended way of adding update callbacks is now `useLoop` composable https://docs.tresjs.org/api/composables.html#useloop 

You can pause it by using:

```
const { onBeforeRender, pause, resume } = useLoop()

onBeforeRender(({ elapsed }) => {
  sphereRef.value.position.y += Math.sin(elapsed) * 0.01
})

pause() // This will pause the loop
resume() // This will resume the loop
```
