### ISSUE TITLE
May be we could use vitepress-plugin-sandpack instead

### ISSUE THREAD

**Issue by jerrywu001** [Tresjs/tres#261]
Sometimes previews fail for example with StackBlitz on mobile. 

But we can use [vitepress-plugin-sandpack](https://github.com/jerrywu001/vitepress-plugin-sandpack) instead. It's a [vitepress plugin](https://vitepress-sandbox.js-bridge.com/get-started/introduction.html),  and the syntax is concise, use the MD syntax directly.

**Setup Steps**
https://vitepress-sandbox.js-bridge.com/custom-usage/custom.html

_**and also support**_ [Use snippets](https://vitepress-sandbox.js-bridge.com/basic-usage/snippets.html)

**Online demo**:
https://vitepress-sandbox.js-bridge.com/vite-templates/vite-vue-ts.html

![image](https://github.com/Tresjs/tres/assets/12525415/a4fe5577-e676-4fa7-97b5-079ec122e242)

**Comment by alvarosabu** [comment]
Ohhhh that was exactly what I was looking for @jerrywu001, I was considering implementing it on my own but it already has it.

I liked Stackblitz demos because they are interactive but it's true that it fails in certain browsers. Maybe we could add this as a fallback even.

Great idea

**Comment by alvarosabu** [comment]
Hi @jerrywu001 we ended up using https://play.tresjs.org/ which is a Tres REPL to replace Stackblitz doc exmaples
