### ISSUE TITLE
Message of canvas 0 height error

### ISSUE THREAD

**Issue by JaimeTorrealba** [Tresjs/tres#263]
**Describe the bug**
Could be the position absolute? or maybe conflict with BulmaCSS.

**Steps**
1. Go to https://serene-mousse-562782.netlify.app/mixHtml
2. Open the console

**Expected behavior**
Clearly the canvas is not 0 height, in fact has window-size property, 

**Screenshots**
![image](https://github.com/Tresjs/tres/assets/63722373/b97610e6-62d5-42ef-a91b-130c4ca7369f)

![image](https://github.com/Tresjs/tres/assets/63722373/c26f57e4-db77-4fc3-93aa-92691856a281)

**Additional context**
Please ignore the Color warning, that's my mistake

**Comment by alvarosabu** [comment]
Hey @JaimeTorrealba thanks for raising this, yes the warning is being triggered with false positives, maybe we could leverage this with a timeout?

**Comment by JaimeTorrealba** [comment]
Maybe just remove, because if you want to use html + TresJs, you'll probably put the canvas behind... that cause the issue

**Comment by alvarosabu** [comment]
PR is welcome :)
