### ISSUE TITLE
Typescript autocompletion doesn't work

### ISSUE THREAD

**Issue by SeryiBaran** [Tresjs/tres#279]
### Describe the bug

I'm use simple code:

```vue
<script lang="ts" setup>
import { TresCanvas } from "@tresjs/core";
</script>

<template>
  <TresCanvas window-size>
    <TresPerspectiveCamera />
    <TresMesh>
      <TresTorusGeometry :args="[1, 0.5, 16, 32]" />
      <TresMeshToonMaterial color="orange" />
    </TresMesh>
    <TresAmbientLight :intensity="1" />
  </TresCanvas>
</template>
```

When I press ctrl + space, it should show TS hints, but they don't:

![image](https://github.com/Tresjs/tres/assets/82605415/262d0e2e-d5e2-40b2-b775-5acf24baf63d)

![image](https://github.com/Tresjs/tres/assets/82605415/5123b0cd-48fc-4169-a0ae-335c26bebce8)

Editor:
- VSCode
- `Vue.volar`
- `Vue.vscode-typescript-vue-plugin`

Packages versions:
- `@tresjs/core`: `^2.1.1`
- `three`: `^0.152.2`
- `typescript`: `^5.0.4`

Github requires reproduction link, but stackblitz don't checks TS in vue sfc. Download and run reproduction project locally.

### Reproduction

https://stackblitz.com/edit/tresjs-basic-aqkqrl?file=src%2FApp.vue

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
    Memory: 540.46 MB / 3.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: master_preferences
    Internet Explorer: 11.0.18362.1
  npmPackages:
    @tresjs/cientos: ^2.0.0 => 2.0.0 
    @tresjs/core: ^2.1.1 => 2.1.1 
    vite: ^4.3.8 => 4.3.8
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hey there @SeryiBaran , thanks for raising this issue. You need to install `threejs` types aswell, `npm install @types/three -D". That's why you are getting all those `any` 

I guess you forked the stackblitz example, I will update it so this is no longer a problem in the future 😉
