### ISSUE TITLE
Add core team, contributors and sponsors page in docs

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#287]
### Description

Add core team, contributors and sponsors page in docs

### Suggested solution

I think we can get this data using Github API (at least for the contributors part) to make it dynamic 

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by userquin** [comment]
@alvarosabu check this script https://github.com/vitest-dev/vitest/blob/main/scripts/update-contributors.ts
