### ISSUE TITLE
v-if is not working correctly

### ISSUE THREAD

**Issue by Tinoooo** [Tresjs/tres#303]
### Describe the bug

Conditionally rendering does not work with `v-if`.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-ewzdtl?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

Use `v-if` on a `TresGroup`and try to make the it's content become visible.

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by bperel** [comment]
I also have the issue. Not sure if it's the same bug or not, but when using a raw mesh instead of a mesh wrapped in a group, the click on "click twice" does toggle the cube off then on... but only once: https://stackblitz.com/edit/stackblitz-starters-bumhz6?file=src%2Fcomponents%2FTheExperience.vue. Same thing if I wrap everything within a `<template>`

**Comment by andretchen0** [comment]
[Here's another pared down StackBlitz with 2 `TresMesh` setups.](https://stackblitz.com/edit/stackblitz-starters-k9jxbi?file=src%2FApp.vue)

In the example:

* If the `v-if` is on a `TresMesh` that's a child of `Scene`, toggling off -> on causes the `TresMesh` to have a `null` parent.
* If the `v-if` is on a `TresMesh` that's a child of a `Group`, toggling off -> on works normally.
