### ISSUE TITLE
Black Canvas in Firefox

### ISSUE THREAD

**Issue by claes-work** [Tresjs/tres#310]
### Describe the bug

It seems like Tres.js is no longer working in Firefox. Even on your official documentation all examles render just a black canvas.
I would really like to use Tres.js in projects of my company, but I am unable to do this if Firefox is not supported or working :(

### Reproduction

https://tresjs.org/guide/

### Steps to reproduce

The first and all other examples of this page.

### System Info

```shell
Windows 10
Firerfiox version 114.0.1 (64-Bit)
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hey, @claes-work thanks for creating this issue.

I just tried the playground on Firefox 114.0.1  (64-bit) and all the scenes are working 
![Screenshot 2023-06-20 at 08 15 47](https://github.com/Tresjs/tres/assets/4699008/059b5445-697a-4ba2-83ca-ab5c0446877e)

The documentation of local scenes work, the only thing that might fail are the Stackblitz demos
![Screenshot 2023-06-20 at 08 14 14](https://github.com/Tresjs/tres/assets/4699008/b13c3cc6-a186-43d1-83a9-06e3b85a7895)

Could you provide more info, like errors or warning on the console? Or a video of your browser.

Thanks

**Comment by claes-work** [comment]
Hi @alvarosabu

I'm not sure what changed over night, but it's working perfectly again. I tried ist multiple times yesterday and even updated my browser. However, sorry for taking your time and thanks for the quick respone.
