### ISSUE TITLE
Boolean props have wrong default value

### ISSUE THREAD

**Issue by Tinoooo** [Tresjs/tres#325]
### Describe the bug

One receives an empty string in the component if a prop is set without an explicit value (like `<TresCanvas disable-render>`). 
Boolean props have the value false instead of undefined by default even if no default is set. I noticed this behavior in EffectComposer.

### Reproduction

https://stackblitz.com/edit/tresjs-basic-rwhajn?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

Use a Tres component with a boolean prop without setting it explicitly and check the value inside of the component.

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Props boolean casting is actually a feature of Vue https://vuejs.org/guide/components/props.html#boolean-casting

**Comment by Tinoooo** [comment]
This bug is not as problematic, as I initially thought. The prop casting happens [here](https://github.com/Tresjs/tres/blob/3975f9ba89d396309ff3d92b10b3f3e253ce173d/src/core/nodeOps.ts#L224), so we are safe 👍.
The problem here were the prop defaults of TresCanvas.
