### ISSUE TITLE
TresAxesHelper not respecting "size" value

### ISSUE THREAD

**Issue by akweidler** [Tresjs/tres#334]
### Describe the bug

TresAxisHelper works but it does not respect the "size" constructor parameter:

`<TresAxesHelper` :size="5" />`

### Reproduction

https://stackblitz.com/edit/tresjs-basic-b64iyv?file=package.json,src%2Fcomponents%2FTheExperience.vue

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @akweidler thanks for reaching out.

If you check the ThreeJS documentation https://threejs.org/docs/index.html?q=Ax#api/en/helpers/AxesHelper there is no property 'size' on the object.

You need to pass it to the instance constructor by using the `:args="[size]"` property (See why [here](https://tresjs.org/api/instances-arguments-and-props.html#arguments)

Let me know if it worked ✌️

**Comment by akweidler** [comment]
Thanks @alvarosabu, that worked!

I see now, the `:args=[]` is for the constructors. Sorry must have read too fast through the documentation and missed it here:
https://tresjs.org/api/instances-arguments-and-props.html#arguments

Cheers!
