### ISSUE TITLE
Allow pointer event handlers on <primitive>

### ISSUE THREAD

**Issue by Tinoooo** [Tresjs/tres#402]
### Description

Currently, <primitive> does not support pointer event handlers.

### Suggested solution

Pointer event handlers should work on <primitive> just like the do on component that inherit from Object3Ds.

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alvarosabu** [comment]
@Tinoooo I just tested it and `click` `pointer-enter` and `pointer-leave` does work 

<img width="943" alt="Screenshot 2024-01-07 at 15 57 00" src="https://github.com/Tresjs/tres/assets/4699008/7e08bf0d-1ac5-4fc2-966e-28e2db803362">

Feel free to open it again if you manage to reproduce it.
