### ISSUE TITLE
TresCanvas Screenshot

### ISSUE THREAD

**Issue by echtme** [Tresjs/tres#408]
### Describe the bug

I'm trying to take a screenshot of the TresCanvas, but get always an empty PNG.

    <TresCanvas ref="tresCanvasRef" clear-color="#aaaaaa" shadows id="modelCanvas">
      <CaptureScreenshot />
      <TresPerspectiveCamera :position="[-150, 470, 220]" :look-at="[0, 0, 0]" />
      <Suspense>
        <primitive :position="[0, -100, 0]" v-if="sceneLoaded" :object="scene" />
      </Suspense>
      <TresAmbientLight :intensity="1.2" color="#ffffff" />
      <TresDirectionalLight :intensity="1" color="#ffffff" :position="[-100, 0, 100]" />
      <TresDirectionalLight :intensity="1" color="#ffffff" :position="[100, 0, 100]" />
      <TresDirectionalLight :intensity="1" color="#ffffff" :position="[0, 200, 0]" />
      <OrbitControls />
    </TresCanvas>
    
       
**CaptureScreenshot:**
    <script setup>
import { useTresContext } from "@tresjs/core";

const { renderer } = useTresContext();

const captureScreenshot = () => {
  const canvas = renderer.value.domElement;
  const url = canvas.toDataURL();
  const link = document.createElement("a");
  link.href = url;
  link.download = "screenshot.png";
  link.click();
};
</script>

### Reproduction

https://stackblitz.com/edit/tresjs-basic-bovwvh?file=tsconfig.json

### Steps to reproduce

npm i
npm run dev

### System Info

```shell
"devDependencies": {
    "@nuxt/devtools": "latest",
    "@nuxtjs/tailwindcss": "^6.8.0",
    "autoprefixer": "^10.4.15",
    "nuxt": "^3.7.3"
  },
  "dependencies": {
    "@tresjs/cientos": "^3.3.0",
    "@tresjs/nuxt": "^1.1.6",
    "@tresjs/post-processing": "^0.4.0",
    "@types/node": "^20.6.0",
    "dom-to-image": "^2.6.0",
    "html2canvas": "^1.4.1",
    "node": "^16.20.2",
    "three": "^0.156.1"
  }
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @echtme the problem is that you are creating the snapshot when the canvas width and height are still 0 and the scene hasn't being mounted yet, use vue lifecycle methods or watch the size of the renderer to trigger the snapshot
