### ISSUE TITLE
v-for please

### ISSUE THREAD

**Issue by zkobrinsky** [Tresjs/tres#413]
### Description

I'm using a v-for to instantiate some TresMeshes (as seen in some of the examples), but I need the v-for to dynamically update, and that doesn't seem to work. Any ideas on how to dynamically update a v-for with tres components?

### Suggested solution

Not sure if this is a module thing, but maybe add a v-for to the TresGroup component?

### Additional context

To clarify, the array being used by the v-for: when it changes, the meshes instantiated by the v-for do not update.

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by zkobrinsky** [comment]
Update: I've been able to force a re-rerender by putting a TresMesh (with a v-for in it) inside a TresGroup, and then changing the group's key to force an update. Not an ideal solution. Am I missing something or is this a feature that needs to be build out?

**Comment by zkobrinsky** [comment]
Update: If I put the v-for inside a group and give it a key, it seems to update, even if I don't mess with the key to force an update. However, it seems to re-render the whole scene.

**Comment by andretchen0** [comment]
Do you have this working now?

To help you out, here's a simple, complete example using `v-for`. 

```
<script setup lang="ts">
import { ref } from 'vue'
import { TresCanvas, useRenderLoop } from '@tresjs/core'

const NUM_SPHERES = 10
const ys = ref(new Array(NUM_SPHERES).fill(0))
useRenderLoop().onLoop(({ elapsed }) => {
  for (let i = 0; i < NUM_SPHERES; i++) {
    ys.value[i] = Math.sin(elapsed + i)
  }
})
</script>

<template>
  <TresCanvas clear-color="#333">
    <TresMesh
      v-for="y, i of ys"
      :key="i"
      :position="[i - (NUM_SPHERES * 0.5), y, 0]"
      :scale="0.5"
    >
      <TresSphereGeometry />
      <TresMeshNormalMaterial />
    </TresMesh>
    <TresGridHelper />
  </TresCanvas>
</template>
```

If that still doesn't help, you might ask for help over on the [TresJS Discord.](https://discord.gg/UCr96AQmWn) 

----

The issue queue isn't really the right channel for this sort of help, especially since we don't have a complete copy of your code.

**Comment by zkobrinsky** [comment]
Thanks, but the issue isn't how to use a v-for. The issue is that there is no reactivity in the v-for. If I update the array that the v-for is using, nothing changes. It's not reactive.

**Comment by andretchen0** [comment]
Ok, I understand now. Thanks for reporting this.

Would you please submit a [bug report](https://github.com/Tresjs/tres/issues/new/choose) with a minimal StackBlitz reproducing the error? (There is a spot for it in the bug report form.) 

I will close the present issue as this is not a feature request and there is no StackBlitz highlighting the bug.

----

Context: [Here is a closed issue on the same topic, but it appears that the proposed solution no longer works.](https://github.com/Tresjs/tres/issues/284)

**Comment by andretchen0** [comment]
@zkobrinsky

I opened [this bug report](https://github.com/Tresjs/tres/issues/415), if you'd like to participate there or just stay up to date on the issue.
