### ISSUE TITLE
v-for not working in some setups

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#415]
### Describe the bug

`v-for` isn't working properly in some circumstances. It seems that pushing to an array works *sometimes* but fails in some circumstances.

## Working v-for

First, a working example: [StackBlitz
](https://stackblitz.com/edit/tresjs-basic-aemt5q?file=src%2Fcomponents%2FTheExperience.vue)

* Open the StackBlitz
* Wait until moving blocks show up in "browser" screen
* Click the "browser" screen to give it focus
* Hit the 'r' key repeatedly to push and pop from the array used by `v-for`

(It's important that there's no camera! OrbitControls are applied to the scene, so move around as necessary.)

## Broken v-for

Now, a broken example: [StackBlitz](https://stackblitz.com/edit/tresjs-basic-4qpht2?file=src%2Fcomponents%2FTheExperience.vue)

Only a camera has been added. Follow the instructions above. Hitting "r" will remove elements from the screen, but never put new elements on screen.

## Expected behavior

These two StackBlitz examples should work the same way.

## Context

* [This old issue](https://github.com/Tresjs/tres/issues/284) was brought up a few months ago, but closed.
* I closed [this recent issue](https://github.com/Tresjs/tres/issues/413) from @zkobrinsky – no reproduction.

----

### Reproduction

https://stackblitz.com/edit/tresjs-basic-4qpht2?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

See StackBlitz examples in the description above.

### System Info

```shell
(From StackBlitz)

  System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.12 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: 3.3.0 => 3.3.0 
    @tresjs/core: 3.2.2 => 3.2.2 
    vite: ^4.3.8 => 4.4.9
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @andretchen0 is this ticket still relevant?

**Comment by andretchen0** [comment]
Closing: ran the reproduction with the `v4` core and the described is no longer present.
