### ISSUE TITLE
MindAR

### ISSUE THREAD

**Issue by FrankBevr** [Tresjs/tres#421]
### Hola 👋 

There is MindAr.
MindAr is a threeJS libary for image tracking and other AR Features.

**Is it possible to integrate it?**

Not too familar with TresJs So far, but maybe with some help.  
I can skretch something out to make a tiny AR Expierience.  
Does someone with more expierience can take a look and some ideas of how to implent it in a really rough way? ^ ^  

### Suggested solution

[React Three Fiber and mindAR integration](https://github.com/tommasoturchi/react-three-mind)

[MindAR - Repo ](https://github.com/hiukim/mind-ar-js)

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by FrankBevr** [comment]
**Added Note:**
I just saw XR is on the road map for next year. Yeay 🎉

**Comment by alvarosabu** [comment]
Yes! I definitely hope to work on XR in general and implement it with the library but honestly have no idea how to start with it. Haha Let's discuss it here

My biggest question @FrankBevr, do I need a headset to test it?

**Comment by FrankBevr** [comment]
No, you dont need a headset, thats the beauty in my opinion🌻

#### If you have 10 minutes, test it
1. `gh repo clone hiukim/mind-ar-js`
2. `cd mind-ar-js`
3. `node --version`
    > v18.18.2
4. `npm install`
5. `npx vite --config vite.config.dev.js`
6. Open a Webbrowser, go to `http://localhost:5173`
7. Click on link, which is named [Three](http://localhost:5173/examples/image-tracking/three.html)
8. accept "allow camera", now you see yourself via your webcam
9. grap your phone and navigate to `https://tinyurl.com/mindar-frank`
10. Hold your phonescreen against your webcam. 
11. 🎉 
12. Go to [Example HTML from Hiukim](https://github.com/hiukim/mind-ar-js/blob/master/examples/image-tracking/three.html)
13. Spend 3 minutes of reading/looking
14. Now you know more than before

#### In General:
The trick with AR is to understand. There is the virtual camera and there is a real camera. You overlay the real camera(webcam) with the virtual camera(ThreeJS Camera). 
The tricky part is to calucalte the position of the real camera 60 times per second.     
> Alias "Where is my picture" "There is my picture" "Where is my picture" "There is my picture" "Where is my picture" "There is my picture" 
> 60 times a second. After each frame adjust the virtual camera a bit

#### More webar libaries: 
[8th Wall](https://www.8thwall.com/)  
[Zappar](https://zap.works/)  
[Babylon AR](https://doc.babylonjs.com/features/featuresDeepDive/webXR/webXRARFeatures#getting-started-with-augmented-reality) 
...

#### Issue of Intregation

MindAR uses his own thing of ThreeJS Camera.  

See this [line](https://github.com/hiukim/mind-ar-js/blob/ce9440684a0733fa838fe85a09f8d85e7ecf9bf4/examples/image-tracking/three.html#L42)

The same in blue via react, this [line](https://github.com/hiukim/mind-ar-js-react/blob/e6ecd03633da55ffcd5136b5fae9c4d97a548832/src/mindar-three-viewer.js#L13)

I don't know yet if thats a actually issue or not, in the react-three-fiber example he just dont use it. See this [line](https://github.com/tommasoturchi/react-three-mind/blob/5868517973939459450821bf5aed7bf6928a4117/src/AR.js#L51) , I think he rips the controller from mindAR out and attach it to his own camera somehow, [this line](https://github.com/tommasoturchi/react-three-mind/blob/5868517973939459450821bf5aed7bf6928a4117/src/AR.js#L80C11-L80C21)
But yeah this code is a bit cumbersome to read, especially if i see updateMatrix, yeah sure completly naturally to update Matrix manually 😅🙈

#### OverAndOut, cheers ✌️

**Comment by alvarosabu** [comment]
@FrankBevr We started to play around with XR just recently here https://github.com/Tresjs/XR 

I see potential as a community package, wdyt?

**Comment by alvarosabu** [comment]
I'm gonna close due to inactivity. Feel free to reopen if someone wants to work on it. But IHMO should be a community package
