### ISSUE TITLE
[Cannot read properties of null (reading 'size')] patchProp does not properly handle camelCase props

### ISSUE THREAD

**Issue by fakedob** [Tresjs/tres#445]
### Describe the bug

I recently found this lib and find it awesome so far! Unfortunately, while I was experimenting with the `TresDirectionalLight` I realised there is an exception thrown when passing `:shadow-map-size-width` or `:shadow-map-size-height` attrs to the component, which seems to work fine in the examples (probably something changed overtime).
The root cause as I can see, comes from `[tres/src/core/nodeOps.ts].patchProp`, which tries to retrieve an inner object prop, based on the attribute name. The problem with `shadow-map-size-height` comes from the fact it must be transpiled into `shadow.mapSize.height`, where the selector becomes `shadow.map.size.height`.

As a temporary solution, I use v-bind on the component attached to object as follows:
```
const shadowConfig = {
  'shadow-mapSize-width': 512,
  'shadow-mapSize-height': 512
}
```

### Reproduction

https://stackblitz.com/edit/tresjs-basic-yslayw

### Steps to reproduce

npm intall && npm run dev
error is being logged in the inspector :/

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Yes, it's a known limitation.

I know is not ideal but try using:

```
<DirectionalLight :shadow-mapSize-width="1024" />
```

And removing the vue attr hypenation rule for your tres components

**Comment by fakedob** [comment]
Hey @alvarosabu thanks for the suggestion, ill use it as proposed :)
