### ISSUE TITLE
Support for Nuxt v2?

### ISSUE THREAD

**Issue by doebi** [Tresjs/tres#453]
### Description

Are you planning on adding support for Nuxt v2 or is there a chance to get it working on a legacy project?

I take that the underlying technologies changed significantly, just wondering if someone got to get it working.

### Suggested solution

This is just a question.

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alvarosabu** [comment]
Hi @doebi interesting quesiton. I would say if you use compatibility mode with composition API it should work. I haven't test it tho
