### ISSUE TITLE
Routing Jump - Problem Occurring

### ISSUE THREAD

**Issue by zhangyijie0214** [Tresjs/tres#475]
### Describe the bug

"Hello, I have two questions:

1.In the custom rendering, it seems that Vue's unmount hooks, 'onUnmounted' and 'onBeforeUnmount', are not working. I'm using 'onLoop', and when I navigate to another page and then return, it creates a new 'onLoop' which runs alongside the previous one, including the 'onLoop' inside 'useFBO'. Currently, I can only unmount them by using 'onLoop.off' at the root canvas component.
2.I am using version 3.5.1, and I've noticed significant frame drops with touch and other events. I'm not sure if this has been optimized in newer versions.
3.I encounter a problem when using 'Tres' on two different pages. When I navigate from page 1 with 'tres' to page 2 with 'tres', nothing is displayed. However, if I go from page 1 with 'tres' to page 3 without 'tres', and then to page 2 with 'tres', this problem does not occur."

### Reproduction

https://github.com/zhangyijie0214/nuxt-tres-test

### Steps to reproduce

npm install
npm run dev

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zhangyijie0214** [comment]
Could it be considered to change 'onUnmounted' to 'onBeforeUnmount'?🤔

**Comment by zhangyijie0214** [comment]
I will solve it this way for now.😓
`watch(()=> isActive.value,()=>{
  if (!isActive.value) {
    resume()
  } 
})`

**Comment by Sea-DH1** [comment]
Is there any progress on this issue?

**Comment by alvarosabu** [comment]
>  Is there any progress on this issue?

Depends on which of the 3 issues inside the ticket you mean 😅, if it is the nuxt router issue is being handled here https://github.com/Tresjs/nuxt/issues/41

**Comment by alvarosabu** [comment]
Hi @zhangyijie0214 since this ticket covers several bugs I would ask you to please create a ticket per issue:

1. New ticket
2. Probably related to https://github.com/Tresjs/tres/issues/436, we are refactoring the pointer event manager on v4
3. For nuxt related issues please open in the correspondent repository, there is one already for the nuxt router issues https://github.com/Tresjs/nuxt/issues/41 

Please edit the title and the description of the video to cover only the first question or close this one and open a new one.

**Comment by zhangyijie0214** [comment]
Sure, I will close this issue and then try the latest version of Tres to see if the first problem still exists, and provide videos and reproduction code.
