### ISSUE TITLE
[Docs] - Advance animations using gsap

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#477]
### Description

We have the basic animations  https://docs.tresjs.org/examples/basic-animations.html with `useRenderLoop`

It would be nice if we add a guide on `Advanced` for more complex animations using `gsap`

### Suggested solution

Add a `advance-animations` page under `/advanced/`

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by DennisSmuda** [comment]
I would like to give this a go 👍

**Comment by Jahan-Shah** [comment]
I would like to help with this too.

**Comment by DennisSmuda** [comment]
@Jahan-Shah nice - should we DM on discord and we can exchange some ideas? 😄

**Comment by Jahan-Shah** [comment]
@DennisSmuda sounds good, Let's do it.

**Comment by DennisSmuda** [comment]
@Jahan-Shah - thanks for the StackBlitz demo code! Feel free to look over the PR, I basically just added some words around it :)

**Comment by Jahan-Shah** [comment]
@DennisSmuda Happy to help. The PR looks fine. Yes I saw the text in the demo, looks cool.
