### ISSUE TITLE
empty Canvas keeps expanding infinitely vertically in CSS

### ISSUE THREAD

**Issue by baumi951** [Tresjs/tres#493]
### Describe the bug

![a4](https://github.com/Tresjs/tres/assets/79602318/133f2852-b1c2-4cf6-8310-2864c26ebbd7)

When i have a simple canvas with Vue Router and a add an empty canvas it keeps expanding forever downwards.

I created a git repo where you can reproduce the bug.

It only happs in portait (smartphone) size of the window.

Quick Workarounds:
- Wrap the Canvas into a div to stop the problem

![image](https://github.com/Tresjs/tres/assets/79602318/8be0fbb3-b945-47dc-a643-1370b09b1c92)

### Reproduction

https://github.com/baumi951/problem1

### Steps to reproduce

- Open the git repo (in github codespace)
- npm run dev
- move window to smartphone size
- press the link "ThreeView"
- You can see the size keeps expanding

### System Info

```shell
Chrome Browser
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
The `TresCanvas` will take the height of its direct parent, so unless you use a `window-size` prop, set some styles to the parent so it doesn't grow infinite.
