### ISSUE TITLE
Are you considering providing a version for Babylon.js after completing this project?

### ISSUE THREAD

**Issue by sheerhr** [Tresjs/tres#502]
### Description

I would like to have a version for Babylon.js

### Suggested solution

I'm currently learning Babylon.js and have noticed some differences in terms of mesh events between Three.js and Babylon.js. Unlike Three.js, Babylon.js provides a mechanism similar to the actionManager on its meshes. I'm curious to know if Cientos has a similar feature. I'm looking forward to seeing how the combination of Vue with Babylon.js will eventually shape a project

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alvarosabu** [comment]
Hi there, thanks for your question, is quite interesting.

TresJS is a custom render on top of ThreeJS, so it's not meant to work with something else. I'm afraid it would be a completely different project and ecosystem. 

I would love to see a Vue custom renderer for BabylonJS, if you are interested on starting one, we can share our experience in creating it.

Cheers!

**Comment by alvarosabu** [comment]
Sure, just let us know how we can help you 😊
