### ISSUE TITLE
docs(sandbox): "Failed to resolve component: TresDirectionalLight"

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#521]
### Describe the bug

<img width="1006" alt="Screenshot 2024-01-21 at 22 33 48 copy" src="https://github.com/Tresjs/tres/assets/20469369/ff81041f-518b-46dc-87a5-d8c4aa16c8c4">

In the [Tres docs](https://docs.tresjs.org/guide/), an error appears in the sandbox:

```
Failed to resolve component: TresDirectionalLight
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
 at <Repl>
```

### Reproduction

N/A

### Steps to reproduce

* in the browser, navigate to https://docs.tresjs.org/guide/
* in the sandbox window, see the error

### System Info

```shell
Tested in:

* Firefox 127.0.1 (Mac ARM)
* Chrome Version 120.0.6099.234 (Mac ARM)
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
@andretchen0 yes this is annoying, for some reason is like the sandbox is not getting the template compiler options 🥲

**Comment by alvarosabu** [comment]
I just solved, there was a fix on the vuejs repl I wasn't aware of
