### ISSUE TITLE
[Devtools]- Memory badge is counting the highlighter component

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#533]
### Describe the bug

When selecting an object, the highlight mesh is counted on the memory consumption badge

We should filter it
https://github.com/Tresjs/tres/assets/4699008/30f52b06-5295-4a57-b05b-19ceaf11c8ac

### Reproduction

Not needed 

### Steps to reproduce

1. Open vue devtools
2. Select and instance and check the badge of memory consuption

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 93.17 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 121.0.6167.139
    Firefox: 121.0.1
    Safari: 17.2.1
  npmPackages:
    @tresjs/cientos: ^3.7.0 => 3.7.0 
    @tresjs/core: ^3.7.0 => 3.7.0 
    @tresjs/eslint-config-vue: ^0.2.1 => 0.2.1 
    @tresjs/leches: ^0.14.0 => 0.14.0 
    @types/three: ^0.161.2 => 0.161.2 
    @vitejs/plugin-vue: ^5.0.3 => 5.0.3 
    three: ^0.161.0 => 0.161.0 
    typescript: ^5.3.3 => 5.3.3 
    vite: ^5.0.12 => 5.0.12 
    vite-plugin-glsl: ^1.2.1 => 1.2.1 
    vue: ^3.4.15 => 3.4.15 
    vue-tsc: ^1.8.27 => 1.8.27
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
@alvarosabu 

Devtools is no longer part of the core, right? Can this be closed?
