### ISSUE TITLE
(v4) Tests without `root` fail

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#551]
### Description

I'm trying to write some simple vitest tests for nodeOps. Here's an example:

```ts
  it ('should not throw on nodeOps.remove', async() => {
    const mesh = nodeOps.createElement('TresMesh')
    const parent = nodeOps.createElement('TresMesh')
    nodeOps.insert(mesh, parent)
    nodeOps.remove(mesh)
  })
```

This test fails with the following error:

```TypeError: deregisterBlockingObjectAtPointerEventHandler is not a function```

### Desired outcome

Insertions/removals without a root shouldn't throw.

### Steps to reproduce

* Insert example into src/core/nodeOps.test.ts
* `pnpm run test:ui`
* See failing test

### Context

Related: #515 

The code that throws [starts at line 137](https://github.com/Tresjs/tres/blob/898a8b1694962ae371591f3ff7ed2659a6b5f1ac/src/core/nodeOps.ts#L137):

```ts
    const ctx = node.__tres
    // remove is only called on the node being removed and not on child nodes.
    node.parent = node.parent || scene
    
    const { 
      deregisterObjectAtPointerEventHandler,
      deregisterBlockingObjectAtPointerEventHandler, 
    } = ctx.root
```

### Proposed solution

Dispatch an event and handle at the root. That would allow the tests to pass and reduce some coupling at the same time.

For what it's worth, [this is how `THREE.Material.dispose()` works](https://github.com/mrdoob/three.js/blob/841d2e791d3e8a2463322c5ca31b16956828b91c/src/materials/Material.js#L508C1-L512C3), which is [called in the Tres code](https://github.com/Tresjs/tres/blob/898a8b1694962ae371591f3ff7ed2659a6b5f1ac/src/core/nodeOps.ts#L150) right below the block shown above.

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @andretchen0 I think @garrlker PR #529 will remove the need to use those methods. But, for tests we will need to mock the root state since its widely used

**Comment by andretchen0** [comment]
@alvarosabu Ok. I'll close the issue here.
