### ISSUE TITLE
Clicking on the scene cannot update model events

### ISSUE THREAD

**Issue by Sea-DH1** [Tresjs/tres#561]
### Describe the bug

If the canvasClick event is removed, it will run normally.
The requirement is to click on a blank area of the scene to modify the model back to its original color.
Is there any way to achieve this?

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-qdxqhm?file=src%2Fcomponents%2FTheExperience.vue

### Steps to reproduce

Run npm install followed by npm run dev

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @Sea-DH1, this is not a bug, if you add a click event handler to the canvas this will interfere with the Tres event manager which is based on [RayCasting](https://threejs.org/docs/#api/en/core/Raycaster)

Although I understand your use-case,  I think we could implement an `onPointerMissed` #515 @garrlker is it something cover by your PR for v4?

**Comment by Sea-DH1** [comment]
After reading the content of the PR, it seems to have solved my problem.
