### ISSUE TITLE
Using .glb suffix files causes the project to become unresponsive？

### ISSUE THREAD

**Issue by estoi** [Tresjs/tres#576]
### Describe the bug

I have a link to a `.glb` suffix file which when I pass to `useGLTF` causes the project to not run properly for a long time.
When I revert to the code in the example it returns to normal

`package.json`
<img width="367" alt="image" src="https://github.com/Tresjs/tres/assets/44252820/626f1b8a-a035-4903-bf0d-0c678459c7bb">
### Reproduction

https://stackblitz.com/edit/tresjs-basic-cxjaef?file=package.json,src%2Fcomponents%2FTheExperience.vue

### System Info

```shell
System:
    OS: macOS 12.7.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 110.54 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.94
    Safari: 17.3.1
  npmPackages:
    @tresjs/cientos: ^3.8.0 => 3.8.0 
    @tresjs/nuxt: ^2.1.1 => 2.1.1
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @estoi, remove the `import` inside of the useGLTF

```
const { scene: model, animations } = await useGLTF(
  import('https://models.readyplayer.me/65e68d86374014375e47f33a.glb')
);
```

You need to pass the URL, not an import. https://stackblitz.com/edit/tresjs-basic-r5sszy?file=src%2Fcomponents%2FTheExperience.vue
