### ISSUE TITLE
`useRenderLoop().onLoop` ticks before the renderer can meaningfully render

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#595]
## Problem

`useRenderLoop().onLoop` ticks before the renderer can meaningfully render. 

When `onLoop` is initially called, e.g.:

* camera.aspect has its default value of 1, regardless of screen aspect
* renderer.domElement.width has a value of 0
* sizes.width has a value of 0

These values change on the subsequent frame, making coding/debugging more difficult than necessary.

## Solution

* `useRenderLoop()` should be dependent on the `context`'s renderer.
* The system shouldn't tick `onLoop` until the renderer is ready. 

## Context

* #251
* #252

### Reproduction

https://stackblitz.com/edit/tresjs-basic-t6zfd2?file=src%2Fcomponents%2FUseRenderer.vue

### Steps to reproduce

See StackBlitz.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.3 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: ^3.5.1 => 3.5.1 
    @tresjs/core: ^3.4.1 => 3.4.1 
    @tresjs/eslint-config-vue: ^0.2.1 => 0.2.1 
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
Hey @alvarosabu !

I saw that you labelled this as `PR welcome`. Great! I'll be happy to submit a PR eventually. 

For now, I'm trying to submit issues highlighting rough spots encountered while building things with Tres.

My hope is that in assembling the issues, we'll be able to knock all (or most) of them out at once.

**Comment by andretchen0** [comment]
## Related?

This issue maybe pops up with custom shaders and HMR.

When doing off-screen rendering using a custom shader, this error is thrown on HMR:

<img width="717" alt="Screenshot 2024-04-04 at 15 13 25" src="https://github.com/Tresjs/tres/assets/20469369/06cb6e48-c9bc-4b41-bf5d-cd25ba699653">

**Comment by alvarosabu** [comment]
This usecase is covered by the new `useLoop` composable available on `v4` https://docs.tresjs.org/api/composables.html#useloop

**Comment by andretchen0** [comment]
Hey @alvarosabu ,

This is still an issue with `onLoop`, as far as I can see. If you modify the code from the docs, this will `console.log` `0, 0`.

```ts
let logged = false
const { off } = render(({ renderer, scene, camera }) => {
  if (!logged) {
    logged = true
    console.log(renderer.domElement.width, renderer.domElement.height)
  }
  renderer.render(scene, camera)
})
```

**Comment by alvarosabu** [comment]
OHHHH ok I see @andretchen0 we could add a check that if the size is !=0 it does render here:

https://github.com/Tresjs/tres/blob/8d53bbae37d858ddf775f0574647e86979473ac4/src/composables/useTresContextProvider/index.ts#L196-L199
