### ISSUE TITLE
`useRenderLoop`: render after updates

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#607]
## Problem

Updates/renders share the same unordered-from-the-components-perspective callback "slot", leading to out-of-sync visuals.

## Example

Here's the Cientos' playground demo for `MeshReflectionMaterial`. Notice the extra "jumps" in the reflection:

https://github.com/Tresjs/tres/assets/20469369/314a4154-7cef-47d0-977e-e98fd53c8c13

Here are two adjacent frames. Notice that the "real" elements haven't moved, but the reflection "jumps" from one frame to the next:

<img width="1044" alt="Screenshot 2024-03-29 at 15 13 35" src="https://github.com/Tresjs/tres/assets/20469369/47a6f2d1-817c-4bf1-a164-70969fb3aa7d">

## Why it happens

The "jumps" occur because the updates/renders are all firing in `onLoop`, but out-of-order from the perspective of the FBO reflection. So for a file like this ...

```vue
<script setup lang="ts">
import { TresCanvas, useRenderLoop } from '@tresjs/core'
import DemoComponent from './DemoComponent.vue'

const { onLoop } = useRenderLoop()

onLoop(({ elapsed }) => {
  console.log("Demo update", elapsed)
})
</script>

<template>
  <TresCanvas>
    <TresPerspectiveCamera />
    <DemoComponent></DemoComponent>
  </TresCanvas>
</template>

```

... a single "tick" of `onLoop` looks like this:

<img width="238" alt="Screenshot 2024-03-29 at 16 41 44" src="https://github.com/Tresjs/tres/assets/20469369/63d33e65-de88-48dc-859d-709863672227">

With this ordering, if `DemoComponent` renders the scene to an FBO, and is then rendered to the screen, it'll always be 1 frame behind `Demo`.

### Suggested solution

We could follow R3F's lead here:

* [Guarantee that rendering happens after `onLoop`](https://docs.pmnd.rs/react-three-fiber/api/hooks#useframe)
* Implement these:
** https://docs.pmnd.rs/react-three-fiber/api/hooks#taking-over-the-render-loop
** https://docs.pmnd.rs/react-three-fiber/api/hooks#negative-indices

For example, R3F's `OrbitControls` uses a negative index:

https://github.com/pmndrs/drei/blob/c147c2b1064bc4b457150f995bf714c2e43cf56f/src/core/OrbitControls.tsx#L58C1-L61C13

If I understand correctly, that means that the OrbitControls camera is updated before the rest of the scene, which is important in the case of FBOs like in the reflection material.

### Alternative

As a simpler – though less flexible – solution, we could add a few callbacks:

* `useRenderLoop().onBeforeRender()` – for FBOs
* `useRenderLoop().onRender()` – for actually rendering to the screen

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alvarosabu** [comment]
Thanks for opening this @andretchen0 is really insightful, I noticed that issue and didn't understand why it was happening but now I understand 🤔

Due to the amount of issues that useRenderLoop is giving lately I'm considering refactoring it to move away from the useRaFn and go for a more vanilla approach to ensure we have a unique loop per instance. 

Any suggestions?

**Comment by andretchen0** [comment]
> Any suggestions?

I don't *think* it'd be hard to roll our own. 

The only part I haven't implemented in other projects is unbinding callbacks transparently when their Vue component is unmounted.

What timeline are you looking at? I've been holding off on discussions and eventual implementations of big changes until `v4` is released.

**Comment by alvarosabu** [comment]
This use-case is covered on the new `useLoop` composable on `v4` https://docs.tresjs.org/api/composables.html#useloop
