### ISSUE TITLE
useSeek, useRaycaster and useLoader are missing from TresJS 3.8.0

### ISSUE THREAD

**Issue by bperel** [Tresjs/tres#619]
### Describe the bug

I am importing useSeek in my project:
```typescript
import { useSeek } from "@tresjs/core";
```

Since the upgrade to Tres 3.8.0, I get the error `Module ""@tresjs/core"" has no exported member "useSeek". Did you mean to use "import useSeek from "@tresjs/core"" instead?`

Indeed, useSeek, useRaycaster and useLoader which are exported in src/composables/index.d.ts don't seem to be present in the package anymore.

### Reproduction

https://www.runpkg.com/?@tresjs/core@3.8.0/dist/src/composables/index.d.ts

### Steps to reproduce

Unfortunately I didn't manage to reproduce the issue on Stackblitz, but the link above shows that the 3 files are missing from the directory where it's supposed to be imported from.

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @bperel thanks for raising this. Seems to be a typing issue because the composable are indeed correctly exported in the package

![Screenshot 2024-04-08 at 10 33 42](https://github.com/Tresjs/tres/assets/4699008/744f4a22-4192-4e02-869d-2aa9efb33e50)

**Comment by danielklein-arch** [comment]
@alvarosabu Hi, just stumbled upon this issue when I was solving the same problem but with useLoader. Based on your response to this issue I guess it will be typing issue as well

**Comment by kleinpetr** [comment]
@alvarosabu I've upgraded deps in the nuxt module we use :) https://github.com/Tresjs/nuxt/pull/91
