### ISSUE TITLE
Minor error in docs- ThisIsPascalCase and thisIsCamelCase

### ISSUE THREAD

**Issue by jonmatthis** [Tresjs/tres#621]
### Describe the bug

In the 'your first scene' doc, you say the 'TresAmbientLight' is camel case. Technically it is PascalCase 😌

### Reproduction

https://docs.tresjs.org/guide/your-first-scene.html

### Steps to reproduce

1. Look at words. 
2. Think of their definitions.
3. Be super pendantic
4. Clutch pearls 😱

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
`ThisSortOfCasing` is called:

* 'CapWords' or 'CamelCase' in the [Python docs](https://legacy.python.org/dev/peps/pep-0008/#descriptive-naming-styles)
* 'PascalCase' or 'UpperCamelCase' on this [Wikipedia page](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Examples_of_multiple-word_identifier_formats)
* 'CamelCase' (sometimes) on this [Wikipedia page](https://en.wikipedia.org/wiki/Camel_case).

If we're going to change the wording to be more specific, I'd personally prefer 'UpperCamelCase' or 'CamelCaps'; 'PascalCase' isn't evocative to me.

**Comment by jonmatthis** [comment]
Oh, I didn't realize there was inconsistency there! Thanks for clarifying.

I agree - the term PascalCase always stood out as a weirdly non-evocative term amid the lovely pantheon of camelCase, kebab-case, snake-case, and (my personal favorite) SCREAMING_SNAKE_CASE


Like, who th is this Pascal guy? Like the gas science guy? What's he got to do with capitalization? 

UpperCamelCase seems like the good choice. 

Thanks for your work!

**Comment by andretchen0** [comment]
> What's he got to do with capitalization?

[Origin of 'PascalCase'](https://learn.microsoft.com/en-us/archive/blogs/brada/history-around-pascal-casing-and-camel-casing) as a term in computer programming.

----

Fwiw, I filed a PR changing "CamelCase" to "UpperCamelCase" in the docs.
