### ISSUE TITLE
Recursive error when using a ref anywhere in the canvas when it changes on a click event handler inside a v-for

### ISSUE THREAD

**Issue by franciscohermida** [Tresjs/tres#649]
### Describe the bug

Doing:
- v-for rendering 3 boxes
- click event handler to set currentItem ref for each box
- using the currentItem ref elsewhere in the canvas

Expecting:
No recursive error

Happening:
recursive error because click handler is called again when ref is being used elsewhere in the canvas

### Reproduction

https://stackblitz.com/edit/tresjs-basic-bskmaj?file=src%2Fcomponents%2FBox.vue

### Steps to reproduce

Click on each of the boxes and check console

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @franciscohermida can you try again with the new v4 to see if it's still happening? Thanks 🙏🏻

**Comment by franciscohermida** [comment]
@alvarosabu seems fixed thanks!

**Comment by franciscohermida** [comment]
@alvarosabu seems fixed thanks!
