### ISSUE TITLE
The click event does not work on GLTFModel

### ISSUE THREAD

**Issue by jackywongmm** [Tresjs/tres#667]
### Describe the bug

 <Suspense>`    
    <GLTFModel @click="(e, r) => console.log(e, r)"  path="/model/K1.glb" draco />
  </Suspense>
`
Am I using it the wrong way？

### Reproduction

null

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jackywongmm** [comment]
`<Suspense>
      <GLTFModel @click="(e, r) => console.log(e, r)"  path="/model/K1.glb" draco />
</Suspense>`

I missed a label. That's the whole

**Comment by jackywongmm** [comment]
and
`<primitive @click="(e) => console.log(e)"  :object="K2"> </primitive>`

**Comment by garrlker** [comment]
We recently went through a mouse event system rewrite for tres v4 that fixes many issues like this.

Can you try installing the latest`@tres/core` release candidate and checking if that fixes your issue?

`npm i @tresjs/core@4.0.0-rc.0`

**Comment by jackywongmm** [comment]
Problem solved. Thanks！

**Comment by garrlker** [comment]
Glad to hear it!
