### ISSUE TITLE
Remove extraneous elements from StackBlitz Bug reproduction starter template

### ISSUE THREAD

**Issue by andretchen0** [Tresjs/tres#669]
## Problem

The StackBlitz template for bug reproductions contains several redundant or extraneous elements. 

* This costs conscientious developers time, as they have to remove many unneeded elements from their bug reports.
* This costs Tres devs time, reading through non-minimal reproductions. 

As a Tres developer, in order to encourage and facilitate minimal bug reproductions, I would like to remove extra elements from the StackBlitz Bug reproduction starter template. 

## Suggested Solution

* Remove the `src/components` folder.
* Replace the code in `./src/App.vue` with the following:

```html
<script setup lang="ts">
import { TresCanvas } from '@tresjs/core';
</script>

<template>
  <TresCanvas>
    <TresMesh>
      <TresBoxGeometry />
      <TresMeshNormalMaterial />
    </TresMesh>
  </TresCanvas>
</template>
```

That makes this the starter template:

<img width="1334" alt="Screenshot 2024-04-28 at 01 55 13" src="https://github.com/Tresjs/tres/assets/20469369/237c9649-7794-4fe4-9c8f-0f749787168a">

### Alternative

Keep as is.

### Additional context

For comparison, here's the current `src/components/TheExperience.vue`. 

It contains:

* unused imports – `extend`, `reactive`
* unnecessary configuration – `const gl = { ... }`
* components that have no visual effect – `<ContactShadows />`, `<TresDirectionalLight />`
* redundant args – `<TresBoxGeometry :args="[1, 1, 1]" />`

```html
<script setup lang="ts">
import { extend } from '@tresjs/core';

import { reactive } from 'vue';
import { BasicShadowMap, SRGBColorSpace, NoToneMapping } from 'three';
import { TresCanvas } from '@tresjs/core';
import { OrbitControls, ContactShadows } from '@tresjs/cientos';

const gl = {
  clearColor: '#82DBC5',
  shadows: true,
  alpha: false,
  shadowMapType: BasicShadowMap,
  outputColorSpace: SRGBColorSpace,
  toneMapping: NoToneMapping,
};
</script>

<template>
  <TresCanvas v-bind="gl">
    <TresPerspectiveCamera :position="[9, 9, 9]" />
    <OrbitControls />
    <TresMesh>
      <TresBoxGeometry :args="[1, 1, 1]" />
      <TresMeshNormalMaterial />
    </TresMesh>
    <ContactShadows />
    <TresDirectionalLight :position="[0, 2, 4]" :intensity="1.2" cast-shadow />
  </TresCanvas>
</template>

```

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alvarosabu** [comment]
Hi @andretchen0 thanks for raising this, I completely agree with most of the points.

The only thing I would keep as it is is the `src/components`, the reason: To promote the good practice of having the `TresCanvas` alone in the `App.vue` and use subcomponents.

This would leverage the amount of issues with context.

**Comment by alvarosabu** [comment]
@andretchen0 I moved it to a new stackblitz inside of the TresJS stackblitz team (it was on my personal before) 

Check it out https://stackblitz.com/~/edit/tresjs-minimal-reproduction and let me know so I can update the suggested reproduction link elsewhere

**Comment by alvarosabu** [comment]
I also created a discussion #670 to solve this in general

**Comment by andretchen0** [comment]
Great! I like the new reproduction template. Much more streamlined.

Closing here.
