### ISSUE TITLE
Showcase link is broken

### ISSUE THREAD

**Issue by wcheek** [Tresjs/tres#676]
### Describe the bug

I wanted to check out the [showcase](https://playground.tresjs.org) but it gives `404`.

### Reproduction

https://playground.tresjs.org

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by NamesMT** [comment]
btw while anyone with permission checks on this issue, cientos doc is also outdated (no `Ocean` component)

**Comment by andretchen0** [comment]
Hey @wcheek ,

Thanks for reporting this. 

I'm guessing the link you clicked was here: https://docs.tresjs.org/guide/#labs (If you found a link outside of the TresJS docs, please point me to it.)

It is indeed pointing to the wrong link. I'll fix it. 

In the meantime, here's what the showcase link should be pointing: https://lab.tresjs.org/

**Comment by andretchen0** [comment]
@NamesMT

Thanks for the report. I'll let the person responsible know.

**Comment by AdrianoCahete** [comment]
Commenting here instead of open another issue:

On [Showcase your work](https://tresjs.org/) section, the "Procedural Synthwave" is pointing to wrong (maybe old?) playground link, at: https://playground.tresjs.org/experiments/synthwave

**Comment by andretchen0** [comment]
@AdrianoCahete 

 > Edit: Even with the new url, the synthwave experiment does not work. Maybe does not exist on playground anymore?

Some Tres project URLs were updated. Projects like synthwave are at lab.tresjs.org now.

https://lab.tresjs.org/experiments/synthwave

I'll push a fix. Thanks for the report!
