### ISSUE TITLE
Unable to set clear-color to transparent

### ISSUE THREAD

**Issue by ASoldo** [Tresjs/tres#679]
### Describe the bug

When i use this snippet I see white background instead of `body/html` with red color. 
```html
    <TresCanvas window-size clear-color="transparent">
```

I want to see html background instead of threejs scene background.

### Reproduction

any project with TresCanvas and set clear-color to transparent

### Steps to reproduce

run any project with Tres and use TresCanvas to set clear-color to transparent.

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ASoldo** [comment]
I had to set `<TresCanvas :alpha="true">...`, I missed that from docs.

**Comment by xwillorg** [comment]
hey,
im trying to make the TresCanvas background transparent but when I use your approach im getting this error: THREE.Color: Unknown color transparent. Is there a new way of making it transparent? I could not find any hint in the docs.

**Comment by ASoldo** [comment]
You need to use :alpha="true" on TresCanvas element. https://docs.tresjs.org/api/tres-canvas.html take a look at props section, first one.

**Comment by xwillorg** [comment]
I did that! My problem was that I used a _TresMeshBasicMaterial_ instead of a _TresMeshStandardMaterial_, this somehow solved my problem.
