### ISSUE TITLE
Helpers diposal error since latest threejs update

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#682]
### Describe the bug

There is an issue with the automatic disposal, some elements like

- GridHelper
- AxesHelper 

Are throwing this error when the scene is unmounted

```
chunk-SRLW6FY7.js?v=a19e4a6b:30745 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dispose')
    at AxesHelper.dispose (chunk-SRLW6FY7.js?v=a19e4a6b:30745:19)
```

### Reproduction

local playground

### Steps to reproduce

- Run playground with `npm run dev`
- Open `conditional` example
- Go back

### System Info

```shell
System:
    OS: macOS 14.3.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 60.73 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
    pnpm: 8.15.4 - ~/Library/pnpm/pnpm
    bun: 1.0.2 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 120.1.61.116
    Chrome: 124.0.6367.207
    Safari: 17.3.1
  npmPackages:
    @tresjs/cientos: 3.8.0 => 3.8.0 
    @tresjs/core: workspace:^ => 4.0.0-rc.0 
    @tresjs/leches: 0.15.0-next.3 => 0.15.0-next.3
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Sea-DH1** [comment]
This version of Box3Helper still has this problem
