### ISSUE TITLE
camera-position bug since version 3.8

### ISSUE THREAD

**Issue by ronny-haberer-at-ottobock-com** [Tresjs/tres#692]
### Description

render-loop initially not rendering
camera having different positions when changing via position = new Vector(x,y,z) or position.set(x,y,z)

### Suggested solution

bugfix

### Additional context

```
<TresCanvas v-bind="canvasSettings">
	<TresPerspectiveCamera v-bind="cameraSettings" />
	<OrbitControls v-bind="controlSettings" />
</TresCanvas>
```

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by ronny-haberer-at-ottobock-com** [comment]
<TresCanvas v-bind="canvasSettings">
			<TresPerspectiveCamera v-bind="cameraSettings" />
			<OrbitControls v-bind="controlSettings" />
</TresCanvas>

**Comment by alvarosabu** [comment]
Hi @ronny-haberer-at-ottobock-com please provide a minimal reproduction of the issue

**Comment by ronny-haberer-at-ottobock-com** [comment]
It's meant like a hint, because I have no time for that - sorry. You can delete if the "reproduction" is needed to align with the process.

**Comment by andretchen0** [comment]
Closing: no reproduction
