### ISSUE TITLE
V4 drops fps

### ISSUE THREAD

**Issue by Dekier** [Tresjs/tres#711]
### Describe the bug

After updating to version 4, my frame rate drops when I move the cursor or zoom in and out of the camera.
Component: 
`CanvasBackground.vue`

Is only one model Icosahedron.

### Reproduction

https://github.com/Dekier/tresjs-drops

### Steps to reproduce

pnpm install
pnpm dev

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by garrlker** [comment]
Hey @Dekier !

Thanks for the reproduction, I'm looking into this issue

**Comment by alvarosabu** [comment]
Hi @Dekier I just checked the reproduction, the icosahedron you are using has a massive detail count. Take a look at the screenshot, I added a wireframe material and the triangles are barely visible

![Screenshot 2024-06-02 at 12 31 20](https://github.com/Tresjs/tres/assets/4699008/30439b19-e10d-4c21-9f77-cb6aab1d40bf)
