### ISSUE TITLE
`Event` is not triggered in `TresGroup`

### ISSUE THREAD

**Issue by hexianWeb** [Tresjs/tres#728]
### Describe the bug

I tried writing this code into `Tresjs v 4.0.2` I think this issue and issue #727 have a common cause
```vue
    <TresGroup>
      <TresMesh
        :position="[0, 0, 0]"
        @click="onClick"
        @double-click="onDoubleClick"
        @pointer-enter="onPointerEnter"
        @pointer-leave="onPointerLeave"
        @pointer-move="onPointerMove"
        @context-menu="onContextMenu"
        @pointer-missed="onPointerMissed"
      >
        <TresBoxGeometry :args="[1, 1, 1]" />
        <TresMeshToonMaterial color="#efefef" />
      </TresMesh>
    </TresGroup>
```
Only `@pointer-missed` has been triggered during this process

https://github.com/Tresjs/tres/assets/59913119/8ca05964-6e9d-4443-a1d8-7e543aebb5fe

### Reproduction

https://stackblitz.com/~/github.com/hexianWeb/starter

### Steps to reproduce

switch the branch to the `bug` branch, or just copy this code into `TheExperience.vue`
```vue 
    <TresGroup>
      <TresMesh
        :position="[0, 0, 0]"
        @click="onClick"
        @double-click="onDoubleClick"
        @pointer-enter="onPointerEnter"
        @pointer-leave="onPointerLeave"
        @pointer-move="onPointerMove"
        @context-menu="onContextMenu"
        @pointer-missed="onPointerMissed"
      >
        <TresBoxGeometry :args="[1, 1, 1]" />
        <TresMeshToonMaterial color="#efefef" />
      </TresMesh>
    </TresGroup>
```
and remove the `TresGroup` near camera
```vue
  <TresGroup>
    <TresPerspectiveCamera :position="[5, 5, 5]" />
  </TresGroup>
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hexianWeb** [comment]
Sorry I removed myself from `Assignees` due to a mistake.

**Comment by garrlker** [comment]
This issue has been resolved

Thanks for the issue and repro @hexianWeb
