### ISSUE TITLE
Rigged models are squished and broken

### ISSUE THREAD

**Issue by alvarosabu** [Tresjs/tres#751]
### Describe the bug

Adding a rigged model with `useGLTF` looks squished and broken

![Screenshot 2024-06-29 at 11 53 14](https://github.com/Tresjs/cientos/assets/4699008/cdaa412f-bc6a-4afa-a741-8eccf0231fd6)

### Reproduction

https://stackblitz.com/~/edit/tresjs-squished-models?file=src/App.vue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @tresjs/cientos: 3.9.0 => 3.9.0 
    @tresjs/core: 4.0.2 => 4.0.0 
    vite: ^5.3.2 => 5.3.2
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/cientos/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/cientos/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://cientos.tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/Tresjs/cientos/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
In case it's useful in the future, here's the change that caused the regression:

https://github.com/Tresjs/tres/commit/79d8a762da6b6e23771a20314f7902eff4635acf#diff-505c62067e9b13b6e4515b24b16c4ac03af37d111601d5a81acf355af29c8fc5L52

Changes to the primitive implementation are currently underway. The model displays and animates as expected with the new WIP implementation:

<img width="340" alt="Screenshot 2024-06-29 at 17 52 57" src="https://github.com/Tresjs/tres/assets/20469369/af93840b-0a4f-497c-8f63-53ee78d2d746">
