### ISSUE TITLE
Sprite - Raycast events not firing if inside group

### ISSUE THREAD

**Issue by dghez** [Tresjs/tres#759]
On `v4` I noticed that if a `Sprite` is inside a `Group`, the events coming from the raycast are not triggered, only the missing one, even if the events are binded to the Sprite itself, not the parent group.
Red is `Sprite+Group`, Blue is `Sprite`

-- ADDITION:
I noticed one interesting thing too. In the demo if you swap the order of the sprites, everything is gonna break
```js
      <SpriteNoGroup />
      <SpriteWithGroup />
 ```
Try to swap e bring the one with the group first, it throws an error.

https://github.com/Tresjs/tres/assets/6367879/cbbe512b-c2f9-4734-be8f-5c985f627555

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yxv5gz?file=components%2FSpriteWithGroup.vue

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by garrlker** [comment]
This issue was fixed by [this PR](https://github.com/Tresjs/tres/pull/731)

When the next version of Tres releases, you should no longer hit this issue

**Comment by dghez** [comment]
@garrlker / @alvarosabu 

Update from my side: i've updated locally on my project to `4.1.0` and is working perfectly on `dev` mode.
Although when I run the build/prod using `nuxt` in production the events are not working anymore. Weird.

Even that, I've updated the stackblitz link here above and weirdly is not working neither in dev mode

**Comment by alvarosabu** [comment]
@dghez hi there. If you are using nuxt with the nuxt module you need to wait for the release there

**Comment by dghez** [comment]
@alvarosabu I've updated to `3.0.1` of the nuxt module and somehow it started to work :) 
So far, for what I see, we can consider it solved :)
