### ISSUE TITLE
Component: The setting parameter disableRender of TresCanvas is ineffective when renderMode is set to always.

### ISSUE THREAD

**Issue by hawk86104** [Tresjs/tres#766]
### Describe the bug

As mentioned in the title, in version v4.1.0

### Reproduction

https://stackblitz.com/edit/tresjs-minimal-reproduction-7tdaba?file=src%2FApp.vue

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hawk86104** [comment]
v4.10  lib file：src/utils/index.ts
`setPrimitiveObject`
`
  // NOTE: copy added/attached Vue children
  // We need to insert `objects` into `newObject` later.
  // In the meantime, `remove(primitive)` will alter
  // the array, so make a copy.
`
I believe there is an issue with this. In the following code, meshOB cannot be operated on.
`html
<primitive :object="gridHelp" />
`
`js
gridHelp.parent 
gridHelp.visible = false
`

**Comment by alvarosabu** [comment]
Actually that prop `disableRender` should be deprecated

**Comment by Neosoulink** [comment]
@alvarosabu I can work on this if no one already working on this one

**Comment by Tinoooo** [comment]
Deprecating the prop is not possible anymore as it already has no effect. I removed it in #838.
