### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by mchao123** [Tresjs/tres#800]
### Describe the bug

Bad types, unpredictable code, and false positives prevent me from using load-on-demand.Consider removing the global type declaration unless I actively add it?

```
'TresPrimitive' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts-plugin(1484)

(alias) type TresPrimitive = TresInstance & {
    object: TresInstance;
    isPrimitive: true;
}
import TresPrimitive
```

### Reproduction

none

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Hi @mchao123, I think what the error is saying is that you have to import the type like this:

```ts
import type { TresPrimitive } from '@tresjs/core`
```

Instead of


```ts
import { TresPrimitive } from '@tresjs/core`
```

If you have the `verbatimModuleSyntax` enabled in your tsconfig. See https://stackoverflow.com/questions/76983697/why-does-my-vue-vite-typescript-application-require-me-to-separate-import-and

**Comment by mchao123** [comment]
I'm using translation software, and there's a bit of a conflict of meaning.

I'm referring to the fact that once I install the dependency, the full component complement exists for my entire project, and the situation gets bad when I use on-demand referencing, which pollutes my global types, yet doesn't pollute them completely, and some of the components are introduced using the 'TresXXX' method, so I'll assume that the TresPrimitive is a surrogate for the 'primitive' tag (in real time yetreports an error and there is no introduction of primitive).

I don't think this issue should be closed.

**Comment by mchao123** [comment]
It's a misrepresentation on my part, it seems that there is no type declaration for "primitive" to be introduced on demand
