### ISSUE TITLE
Stencils seem not to work

### ISSUE THREAD

**Issue by AndreasFaust** [Tresjs/tres#876]
### Describe the bug

I am trying to reproduce Drei’s [Mask](https://github.com/pmndrs/drei/blob/master/src/core/Mask.tsx) component.
I have set up a red sphere as a mask for an orange plane behind it. 
The sphere should be invisible and the plane should only be visible through the mask of the invisible sphere.
Unfortunately it does not work. Am I doing something wrong or has it something to do with TresJS?

INFO: To make it work in React `colorWrite` must be set to `false`. I set it to `true`, because the Sphere would be invisible otherwise.  

### Reproduction

https://stackblitz.com/edit/vitejs-vite-zqtnhb?file=src%2FApp.vue

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by andretchen0** [comment]
I can confirm. 

I've encountered the same recently when trying to make a `<Mask />` component for Cientos.

**Comment by AndreasFaust** [comment]
Thank you @andretchen0! Adding the `stencil`-prop to `TresCanvas` made it work!
I updated my example on `stackblitz`. Also thank you for these amazing libraries!

**Comment by andretchen0** [comment]
Great to hear! Thanks for following up!
