### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by im-aeo** [Tresjs/tres#884]
### Description

Im probably dumb for asking this but, How do i import and texturize wavefront object files?

### Suggested solution

I wanted to use something like       
```
<OBJModel path="/models/AkuAku.obj" />
```
but no-where in the docs does it mention wavefront obj.

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by andretchen0** [comment]
Closing: looking for support. Redirected to Discord.
